#!/usr/bin/env bash
# Margin — self-hosted read-later server. Copyright (C) 2026 Marc Schlienger
# Licensed under the GNU AGPL v3.0 or later; see the LICENSE file for details.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Regenerate deploy/constraints.txt — the exact versions an install gets.
#
#   bash deploy/make-constraints.sh [PYTHON]
#
# requirements.txt states lower bounds, which is what Margin needs and what
# is worth reading. Every install resolves those afresh, so two installs a
# month apart are not the same software, and a service that worked on Friday
# can fail on Monday for reasons nothing in the repository records. The
# constraints file pins one resolution; install.sh applies it when it is
# there and resolves freely when it is not.
#
# Run this on the machine and the interpreter the instances run on. Wheels
# and dependency markers differ by platform and by Python version, so a file
# generated on a laptop describes the laptop. Then run the test suite against
# the result before committing it — a pin nobody tested is a guess with a
# version number.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
PYTHON="${1:-python3}"
OUT="deploy/constraints.txt"

if ! "$PYTHON" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)'
then
  echo "Margin needs Python 3.10 or newer; $PYTHON is older." >&2
  exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "==> Resolving requirements.txt with $PYTHON"
"$PYTHON" -m venv "$WORK/venv"
"$WORK/venv/bin/pip" install --upgrade pip -q
"$WORK/venv/bin/pip" install -r requirements.txt -q

# pip and its own build tooling are not dependencies of Margin; pinning
# them here would only fight the installer's own upgrade step.
{
  "$WORK/venv/bin/python" - <<'PY'
import sys
where = f"Python {sys.version_info.major}.{sys.version_info.minor}, {sys.platform}"
print("# Generated by deploy/make-constraints.sh — do not edit by hand.")
print(f"# Resolved from requirements.txt on {where}.")
print("# Regenerate on the same platform and interpreter the instances run")
print("# on, and run the test suite against the result before committing.")
PY
  "$WORK/venv/bin/pip" freeze --exclude-editable \
    | grep -viE '^(pip|setuptools|wheel|pkg_resources)([=<>!~]|$)' \
    | sort -f
} > "$OUT"

echo "==> Wrote $OUT"
echo "    $(grep -vc '^#' "$OUT") packages pinned. Now run the tests:"
echo "      .venv/bin/python -m pytest"
